# Generated by Django 6.0.7 on 2026-07-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("extraction", "0002_stampanalysis_stamp_image_foreign_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="StampRecognition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("provider", models.CharField(max_length=100)),
                (
                    "raw_result",
                    models.JSONField(blank=True, default=dict),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stamp_analysis",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recognition",
                        to="extraction.stampanalysis",
                    ),
                ),
            ],
        ),
    ]
