# Generated by Django 6.0.7 on 2026-07-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recognition", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecognitionUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField()),
                (
                    "request_count",
                    models.PositiveIntegerField(default=0),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
