# Generated by Django 6.0.7 on 2026-07-28 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StampAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cropped_stamp', models.ImageField(upload_to='extraction/stamps/')),
                ('width_mm', models.FloatField()),
                ('height_mm', models.FloatField()),
                ('ocr_text', models.TextField(blank=True)),
                ('image_description', models.CharField(blank=True, max_length=500)),
                ('dominant_colors', models.JSONField(blank=True, default=list)),
                ('raw_result', models.JSONField(blank=True, default=dict)),
                ('extraction_model_version', models.CharField(max_length=100)),
                ('ocr_model_version', models.CharField(max_length=100)),
                ('tagging_model_version', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stamp_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='ingestion.stampimage')),
            ],
        ),
        migrations.CreateModel(
            name='StampTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('stamp_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='extraction.stampanalysis')),
            ],
        ),
    ]
