# Generated by Django 6.0.7 on 2026-07-31 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recognition', '0002_recognitionusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StampPriceEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(max_length=500)),
                ('provider', models.CharField(max_length=100)),
                ('estimated_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('median_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mean_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('minimum_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('maximum_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('confidence', models.CharField(max_length=20)),
                ('comparable_count', models.PositiveIntegerField()),
                ('comparable_sales', models.JSONField(blank=True, default=list)),
                ('raw_result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stamp_recognition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_estimate', to='recognition.stamprecognition')),
            ],
        ),
    ]
