# Generated by Django 6.0.7 on 2026-08-14 11:32

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StampReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cropped_stamp', models.ImageField(upload_to='report/stamps/')),
                ('width_mm', models.FloatField()),
                ('height_mm', models.FloatField()),
                ('ocr_text', models.TextField(blank=True)),
                ('dominant_colors', models.JSONField(blank=True, default=list)),
                ('recognized_name', models.CharField(max_length=500)),
                ('research_source_url', models.URLField(max_length=2000)),
                ('research_description', models.TextField()),
                ('research_questions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list)),
                ('research_answers', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list)),
                ('estimated_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('median_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mean_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('minimum_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('maximum_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_currency', models.CharField(max_length=3)),
                ('price_confidence', models.CharField(max_length=20)),
                ('summary', models.TextField()),
                ('summary_provider', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stamp_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='ingestion.stampimage')),
            ],
        ),
        migrations.CreateModel(
            name='ReportTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('stamp_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='report.stampreport')),
            ],
        ),
    ]
