# Generated by Django 6.0.7 on 2026-08-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stampreport',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='stampreport',
            name='maximum_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='stampreport',
            name='mean_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='stampreport',
            name='median_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='stampreport',
            name='minimum_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='stampreport',
            name='price_confidence',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='stampreport',
            name='price_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='stampreport',
            name='recognized_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='stampreport',
            name='research_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='stampreport',
            name='research_source_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='stampreport',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='stampreport',
            name='summary_provider',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
