# Generated by Django 6.0.7 on 2026-08-20 11:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extraction', '0002_stampanalysis_stamp_image_foreign_key'),
        ('ingestion', '0001_initial'),
        ('pricing', '0001_initial'),
        ('recognition', '0002_recognitionusage'),
        ('report', '0002_alter_stampreport_estimated_price_and_more'),
        ('research', '0003_stamp_research_qa'),
        ('summarization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StampProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('celery_task_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('queued', 'Queued'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('succeeded_with_warnings', 'Succeeded with warnings'), ('failed', 'Failed')], default='initiated', max_length=32)),
                ('current_step', models.CharField(blank=True, choices=[('extraction', 'Extraction'), ('recognition', 'Recognition'), ('research', 'Research'), ('pricing', 'Pricing'), ('final_report', 'Final report')], max_length=32, null=True)),
                ('step_statuses', models.JSONField(blank=True, default=dict)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_job', to='report.stampreport')),
                ('stamp_analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_jobs', to='extraction.stampanalysis')),
                ('stamp_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='ingestion.stampimage')),
                ('stamp_price_estimate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_jobs', to='pricing.stamppriceestimate')),
                ('stamp_recognition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_jobs', to='recognition.stamprecognition')),
                ('stamp_research', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_jobs', to='research.stampresearch')),
                ('stamp_summary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_jobs', to='summarization.stampsummary')),
            ],
        ),
    ]
