# Generated by Django 6.0.7 on 2026-08-20 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processingjob', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stampprocessingjob',
            name='stamp_analysis',
        ),
        migrations.RemoveField(
            model_name='stampprocessingjob',
            name='stamp_price_estimate',
        ),
        migrations.RemoveField(
            model_name='stampprocessingjob',
            name='stamp_recognition',
        ),
        migrations.RemoveField(
            model_name='stampprocessingjob',
            name='stamp_research',
        ),
        migrations.RemoveField(
            model_name='stampprocessingjob',
            name='stamp_summary',
        ),
    ]
