# Generated by Django 6.0.7 on 2026-08-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processingjob', '0002_remove_stampprocessingjob_stamp_analysis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stampprocessingjob',
            name='current_step',
            field=models.CharField(blank=True, choices=[('extraction', 'Extraction'), ('recognition', 'Recognition'), ('research', 'Research'), ('pricing', 'Pricing'), ('summary', 'Summary'), ('final_report', 'Final report')], max_length=32, null=True),
        ),
    ]
