# Generated by Django 6.0.7 on 2026-07-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("recognition", "0002_recognitionusage"),
    ]

    operations = [
        migrations.CreateModel(
            name="StampResearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("search_query", models.CharField(max_length=500)),
                ("article_title", models.CharField(max_length=500)),
                ("article_url", models.URLField(max_length=2000)),
                ("description", models.TextField()),
                (
                    "raw_result",
                    models.JSONField(blank=True, default=dict),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stamp_recognition",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research",
                        to="recognition.stamprecognition",
                    ),
                ),
            ],
        ),
    ]
