# Generated by Django 6.0.7 on 2026-07-31 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recognition', '0002_recognitionusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StampSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('provider', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('input_snapshot', models.JSONField(default=dict)),
                ('raw_result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stamp_recognition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='recognition.stamprecognition')),
            ],
        ),
    ]
